tunnel: XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
credentials-file: /etc/cloudflared/XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX.json 
ingress:
  - hostname: foobar.shivanandpatil.co 
    service: http://wordpress:80
  - service: http_status:404

